package telegram

import (
	"context"
	"fmt"
	"time"

	"github.com/gotd/td/telegram/message"
	"github.com/gotd/td/tg"

	"github.com/73ai/openbotkit/store"
)

// InputPeerFor rebuilds the MTProto peer for a stored chat. Access hashes are
// recorded during sync precisely so sending needs no extra lookup.
func InputPeerFor(chat *Chat) (tg.InputPeerClass, error) {
	kind, rawID := SplitChatID(chat.ChatID)
	switch kind {
	case PeerUser:
		if chat.AccessHash == 0 {
			return nil, fmt.Errorf("no access hash for user %d — run 'obk telegram sync' first", rawID)
		}
		return &tg.InputPeerUser{UserID: rawID, AccessHash: chat.AccessHash}, nil
	case PeerGroup:
		return &tg.InputPeerChat{ChatID: rawID}, nil
	case PeerChannel:
		if chat.AccessHash == 0 {
			return nil, fmt.Errorf("no access hash for channel %d — run 'obk telegram sync' first", rawID)
		}
		return &tg.InputPeerChannel{ChannelID: rawID, AccessHash: chat.AccessHash}, nil
	default:
		return nil, fmt.Errorf("unknown peer kind for chat %d", chat.ChatID)
	}
}

// SendText sends a message and echoes it into the local store, so a sent
// message is queryable without waiting for it to come back over updates.
func SendText(ctx context.Context, api *tg.Client, db *store.DB, input SendInput) (*SendResult, error) {
	if input.Text == "" {
		return nil, fmt.Errorf("message text is empty")
	}

	chat, err := GetChat(db, input.ChatID)
	if err != nil {
		return nil, fmt.Errorf("look up chat: %w", err)
	}
	if chat == nil {
		return nil, fmt.Errorf("unknown chat %d — run 'obk telegram sync' first", input.ChatID)
	}

	peer, err := InputPeerFor(chat)
	if err != nil {
		return nil, err
	}

	// random_id is generated by the sender.
	updates, err := message.NewSender(api).To(peer).Text(ctx, input.Text)
	if err != nil {
		return nil, fmt.Errorf("send message: %w", err)
	}

	result := sentMessageFrom(updates)
	if result.Timestamp.IsZero() {
		result.Timestamp = time.Now().UTC()
	}

	selfID, _, _ := LoadSelf(db)
	msg := &Message{
		MessageID:  result.MessageID,
		ChatID:     input.ChatID,
		SenderID:   selfID,
		Text:       input.Text,
		Timestamp:  result.Timestamp,
		IsOutgoing: true,
	}
	if err := SaveMessage(db, msg); err != nil {
		return nil, fmt.Errorf("save sent message: %w", err)
	}

	chat.LastMessageAt = &result.Timestamp
	if err := UpsertChat(db, chat); err != nil {
		return nil, fmt.Errorf("upsert chat: %w", err)
	}

	return result, nil
}

// sentMessageFrom digs the assigned message ID and date out of the send
// response. Telegram reports these differently per update container.
func sentMessageFrom(u tg.UpdatesClass) *SendResult {
	result := &SendResult{}

	switch v := u.(type) {
	case *tg.UpdateShortSentMessage:
		result.MessageID = v.ID
		result.Timestamp = time.Unix(int64(v.Date), 0).UTC()
		return result
	case *tg.UpdateShortMessage:
		result.MessageID = v.ID
		result.Timestamp = time.Unix(int64(v.Date), 0).UTC()
		return result
	case *tg.Updates:
		applySentUpdates(result, v.Updates)
		if result.Timestamp.IsZero() && v.Date > 0 {
			result.Timestamp = time.Unix(int64(v.Date), 0).UTC()
		}
	case *tg.UpdatesCombined:
		applySentUpdates(result, v.Updates)
		if result.Timestamp.IsZero() && v.Date > 0 {
			result.Timestamp = time.Unix(int64(v.Date), 0).UTC()
		}
	}
	return result
}

func applySentUpdates(result *SendResult, updates []tg.UpdateClass) {
	for _, upd := range updates {
		switch v := upd.(type) {
		case *tg.UpdateMessageID:
			result.MessageID = v.ID
		case *tg.UpdateNewMessage:
			applySentMessage(result, v.Message)
		case *tg.UpdateNewChannelMessage:
			applySentMessage(result, v.Message)
		}
	}
}

func applySentMessage(result *SendResult, raw tg.MessageClass) {
	msg, ok := raw.(*tg.Message)
	if !ok {
		return
	}
	result.MessageID = msg.ID
	result.Timestamp = time.Unix(int64(msg.Date), 0).UTC()
}
